### ISSUE TITLE
Github action sstill not working

### ISSUE THREAD

**Issue by bernalde** [SECQUOIA/APSE_Notebooks#15]
I think it might be worth integrating the steps in this example https://jupyterbook.org/en/stable/publish/gh-pages.html#automatically-host-your-book-with-github-actions to get it to work (currently failing because of a version issue with sphinx.

**Comment by ZedongPeng** [comment]
Resolved.
https://github.com/SECQUOIA/APSE_Notebooks/actions/runs/6243923621/job/16950075424
